devskiller-code-9Q6R-6WP2-ADYA-S0F/devskiller-code-9Q6R-6WP2-ADYA-S0F/leave/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView

from leave import views

app_name = "leave"

urlpatterns = [
    re_path(r"^$", RedirectView.as_view(url="leave/list")),
    re_path(r"^leave/list$", views.LeaveRequestList.as_view(), name="LeaveRequestList"),
    re_path(
        r"^leave/create$", views.LeaveRequestCreate.as_view(), name="LeaveRequestCreate"
    ),
    re_path(
        r"^leave/(?P<pk>[\d]+)/$",
        views.LeaveRequestDetail.as_view(),
        name="LeaveRequestDetail",
    ),
    re_path(
        r"^leave/(?P<pk>[\d]+)/update$",
        views.LeaveRequestUpdate.as_view(),
        name="LeaveRequestUpdate",
    ),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('register', views.register, name="register"),
]

devskiller-code-9Q6R-6WP2-ADYA-S0F/devskiller-code-9Q6R-6WP2-ADYA-S0F/website/urls.py
"""website URL Configuration"""
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path

sitemaps = {}

urlpatterns = [
    path(r"admin/", admin.site.urls),
    # re_path(r"admin/", admin.site.urls),
    re_path(r"i18n/", include("django.conf.urls.i18n")),
    re_path(r"accounts/", include("django.contrib.auth.urls")),
    re_path(r"", include("leave.urls")),
]

devskiller-code-9Q6R-6WP2-ADYA-S0F/devskiller-code-9Q6R-6WP2-ADYA-S0F/leave/models.py
from enum import IntEnum
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from website import settings
from django.db import models


"""MODEL MANAGER"""
class NewUserManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_active = True
		user.is_superuser = True
		user.save(using=self._db)
		return user




# class User(AbstractUser):
class User(AbstractBaseUser):
    email 					= models.EmailField(max_length=60, unique=True)
    username 				= models.CharField(max_length=30, unique=True)
    manager                 = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)
    date_joined				= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login				= models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin				= models.BooleanField(default=False, verbose_name="admin",)
    is_active				= models.BooleanField(default=True, verbose_name="active",)
    is_verified				= models.BooleanField(default=False, verbose_name="verified",)
    is_staff				= models.BooleanField(default=False, verbose_name="staff",)
    is_superuser			= models.BooleanField(default=False, verbose_name="superuser",)
    language                = models.CharField(max_length=3, default="en")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = NewUserManager()
	
    def __str__(self):
        return self.email 	# For checking permissions. to keep it simple all admin have ALL permissons
	
    def has_perm(self, perm, obj=None):
        return self.is_admin 	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
        
    def has_module_perms(self, app_label):
        return True

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"
        default_related_name = "org_user"
    

class LeaveRequestStatus(IntEnum):
    open = 0
    accepted = 1
    rejected = 2
    closed = 3


STATUSES = tuple((item.value, item.name) for item in list(LeaveRequestStatus))


class LeaveRequest(models.Model):
    start = models.DateField()
    end = models.DateField()
    request_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="days_off" # "leave.User"
    )
    request_ts = models.DateTimeField(auto_now_add=True) # chaned this to set automatically
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="requests" # "leave.User"
    )
    status = models.PositiveSmallIntegerField(
        default=LeaveRequestStatus.open, choices=STATUSES
    )
    review_ts = models.DateTimeField(null=True, blank=True)


    def __str__(self):
        return self.request_by.username + " for @ {self.start} to {self.end}" 

    class Meta:
        verbose_name = "LeaveRequest"
        verbose_name_plural = "LeaveRequests"

devskiller-code-9Q6R-6WP2-ADYA-S0F/devskiller-code-9Q6R-6WP2-ADYA-S0F/leave/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseBadRequest, HttpResponseForbidden, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.shortcuts import redirect, render, resolve_url
from django.core.paginator import Paginator
from django.core.exceptions import PermissionDenied

from leave import models


class LeaveRequestList(LoginRequiredMixin, ListView):
    template_name = "leave/LeaveRequest/list.html"
    model = models.LeaveRequest
    paginator = Paginator
    paginate_by = 20


class LeaveRequestCreate( CreateView):
    template_name = "leave/LeaveRequest/form.html"
    model = models.LeaveRequest
    fields = ("start", "end")

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.instance.manager = self.request.user
        form.instance.request_by = self.request.user
        # TODO: Setup user foreign keys from request here
        return form
    
    def dispatch(self, request, *args, **kwargs):
        # object = self.get_object()
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse("admin:index"))
        
        return render(request, "leave/LeaveRequest/form.html")

    def get_success_url(self):
        return reverse('leave:LeaveRequestDetail', kwargs={'pk': self.object.pk})

class LeaveRequestDetail(LoginRequiredMixin, DetailView):
    template_name = "leave/LeaveRequest/detail.html"
    model = models.LeaveRequest

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        leave_request = self.get_object()
        if leave_request.status == 1 or leave_request.status == 2:
            return redirect(resolve_url("leave:LeaveRequestList"))
        if leave_request.status in {0, 1}:
            return HttpResponseBadRequest('Please set correct status: {}'.format(request.method), \
                                      status=405)
        return HttpResponseForbidden()
    
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        object = self.get_object()
        # self.object = self.get_object()
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse("leave:login"))
        if object.manager != request.user:
            raise PermissionDenied()
        context = super(LeaveRequestDetail, self).get_context_data(*args, **kwargs)
        return render(request, self.template_name, context)

class LeaveRequestUpdate(UserPassesTestMixin, UpdateView):
    template_name = "leave/LeaveRequest/form.html"
    model = models.LeaveRequest
    fields = ("start", "end")
    # authenticated_redirect_url = reverse_lazy(u"view_url")

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse("leave:login"))
        if request.user.is_authenticated:
            return redirect("LeaveRequestDetail", pk=object.pk)
        if object.request_by != request.user:
            raise PermissionDenied()
        return render(request, "leave/LeaveRequest/form.html")



def login(request):
    return render(request, "auth/login.html")

def logout(request):
    return render(request, "auth/logout.html")

def register(request):
    return render(request, "auth/register.html")

devskiller-code-9Q6R-6WP2-ADYA-S0F/devskiller-code-9Q6R-6WP2-ADYA-S0F/leave/templates/leave/LeaveRequest/detail.html
{% extends "leave/base.html" %}
{% block content %}
  <table>
    <tr>
      <th>Request by</th>
      <td>{{ object.request_by.get_full_name }}</td>
    </tr>
    <tr>
      <th>Start</th>
      <td>{{ object.start }}</td>
    </tr>
    <tr>
      <th>End</th>
      <td>{{ object.end }}</td>
    </tr>
    <tr>
      <th>Manager</th>
      <td>{{ object.manager.get_full_name }}</td>
    </tr>
    <tr>
      <th>Status</th>
      <td>{{ object.status }}</td>
    </tr>
    <tr>
      <th>Review timestamp</th>
      <td>{{ object.review_ts }}</td>
    </tr>
  </table>
  {% if object.manager == request.user %}
    <form action="" method="POST">
      {% csrf_token %}
      <button type=submit name="status" value="accepted">Accept</button>
      <button type=submit name="status" value="rejected">Reject</button>
    </form>
  {% endif %}
  {% if object.request_by == request.user %}
    <p>
      <a class="button" href="{% url "leave:LeaveRequestUpdate" object.pk %}">Update</a>
    </p>
  {% endif %}
{% endblock %}

devskiller-code-9Q6R-6WP2-ADYA-S0F/devskiller-code-9Q6R-6WP2-ADYA-S0F/leave/templates/leave/LeaveRequest/form.html
{% extends "leave/base.html" %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Submit request</button>
  </form>
{% endblock %}

devskiller-code-9Q6R-6WP2-ADYA-S0F/devskiller-code-9Q6R-6WP2-ADYA-S0F/leave/templates/leave/LeaveRequest/list.html
{% extends 'leave/base.html' %}
{% comment %}

TODO: Make sure empty values won't show as "None"
TODO: Instead of Status number show it's name

{% endcomment %}
{% block content %}
  <div class="">
    <table class="">
      <thead>
      <tr>
        <th>Submitted</th>
        <th>Requested by</th>
        <th>Start</th>
        <th>End</th>
        <th>Manager</th>
        <th>Status</th>
        <th>Review timestamp</th>
      </tr>
      </thead>
      <tbody>
      {% for object in object_list %}
        <tr>
          <td><a href="{% url 'leave:LeaveRequestDetail' object.pk %}">{{ object.request_ts }}</a></td>
          <td>{{ object.request_by.get_full_name }}</td>
          <td>{{ object.start }}</td>
          <td>{{ object.end }}</td>
          <td>{{ object.manager.get_full_name }}</td>
          <td>{{ object.status}}</td>
          <td>{{ object.review_ts }}</td>
        </tr>
      {% endfor %}
      </tbody>
      <tfoot>
      </tfoot>
    </table>
    {% if is_paginated %}
      <div class="">
        <div class="pagination-container" style="display: flex;align-items: center; flex-direction: row; margin: 1em">
          {% if page_obj.has_previous %}
            <span class="previous">
                <a class="button pseudo" href="?page={{ page_obj.previous_page_number }}">
                    Previous
                </a>
                </span>
          {% endif %}
          <ul style="display: flex; margin: 0; padding: 0">
            {% for page in page_obj.paginator.page_range %}
              <li style="display: flex">
                <a class="button {% if page_obj.number != page %}pseudo{% endif %}" href="?page={{ page }}">{{ page }}</a>
              </li>
            {% endfor %}
          </ul>
          {% if page_obj.has_next %}
            <span class="next">
                <a class="button pseudo" href="?page={{ page_obj.next_page_number }}">
                    Next
                </a>
                </span>
          {% endif %}
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

devskiller-code-9Q6R-6WP2-ADYA-S0F/devskiller-code-9Q6R-6WP2-ADYA-S0F/leave/templates/leave/base.html
{% extends "base/layout/page.html" %}
{% comment %}
As the developer of this package, don't place anything here if you can help it
since this allows developers to have interoperability between your template
structure and their own.

Example: Developer melding the 2SoD pattern to fit inside with another pattern::

    {% extends "base.html" %}
    {% load static %}

    <!-- Their site uses old school block layout -->
    {% block extra_js %}

        <!-- Your package using 2SoD block layout -->
        {% block javascript %}
            <script src="{% static 'js/ninja.js' %}" type="text/javascript"></script>
        {% endblock javascript %}

    {% endblock extra_js %}
{% endcomment %}

devskiller-code-9Q6R-6WP2-ADYA-S0F/devskiller-code-9Q6R-6WP2-ADYA-S0F/templates/base/layout/body.html
<!DOCTYPE html>
<!--
    This is a programming test website for Django
    Author: Janusz Skonieczny @wooyek
-->
<html lang="{{ request.LANGUAGE_CODE }}">
<head>
  <meta charset="UTF-8">
  <title>{% block page_title %}{% endblock %}</title>
  <!-- Picnic is not quite the UX we would hope for, but it works with plain HTML -->
  <link href="https://unpkg.com/picnic" rel="stylesheet">
</head>
<body>
<section style="margin: 1em">
{% block body %}{% endblock %}
</section>
</body>
</html>

devskiller-code-9Q6R-6WP2-ADYA-S0F/devskiller-code-9Q6R-6WP2-ADYA-S0F/templates/base/layout/page.html
{% extends "base/layout/body.html" %} {% block body %}
<nav class="">
    <a href="/" class="brand">
        <span>Leave request management</span>
    </a>

    <!-- responsive-->
    <input id="bmenub" type="checkbox" class="show">
    <label for="bmenub" class="burger pseudo button">menu</label>

    <div class="menu">
        <a href="{% url 'admin:index' %}" class="pseudo button">Admin</a>
        <a href="{% url 'leave:LeaveRequestList' %}" class="pseudo button">Request list</a>
        <a href="{% url 'leave:LeaveRequestCreate' %}" class="button">Create request</a>
    </div>
</nav>
<section class="content" style="margin-top: 4em">
    <section id="alerts">
        {% if messages %} {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissable ">
            <div>
                {{ message|safe }}
            </div>
        </div>
        {% endfor %} {% endif %}
    </section>
    {% block content %}
    <h3>Your templates need work</h3>
    <p>You are looking at a sample text in your app template `templates/base.html`</p>
    {% endblock %}
</section>
<footer>
    <p>You are logged in as: {{ request.user.username }}</p>
</footer>
{% endblock %}